# Generated by Django 6.0.3 on 2026-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditlog_school_feepayment_feestructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='auto_generate_remarks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
