# Generated by Django 6.0.3 on 2026-05-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_feepayment_checkout_request_id_feepayment_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('competency_tagged', models.CharField(choices=[('Communication', 'Communication and Collaboration'), ('Critical Thinking', 'Critical Thinking and Problem Solving'), ('Creativity', 'Creativity and Imagination'), ('Citizenship', 'Citizenship'), ('Learning to Learn', 'Learning to Learn'), ('Self-Efficacy', 'Self-Efficacy'), ('Digital Literacy', 'Digital Literacy')], max_length=50)),
                ('evidence_image', models.ImageField(upload_to='cbc_evidence/')),
                ('teacher_notes', models.TextField(blank=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_gallery', to='accounts.studentprofile')),
            ],
        ),
    ]
