# Generated by Django 6.0.3 on 2026-05-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cbcevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='accounts.studentprofile'),
        ),
    ]
